
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkenlcfjposyiccejqkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrZW5sY2ZqcG9zeWljY2VqcWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwOTM0ODAsImV4cCI6MjA1NzY2OTQ4MH0.2w3ZYloYYMYzMwlbHJs8OBMH_a3NGw7sepd-i6V00Mk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
